### ISSUE TITLE
error when trying to login  after trying to add a new user comment

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#223]
if you try to login when trying to add a user comment from a gene page you get an error

*** File: /usr/local/tomcat_instances/PlasmoDB/logs/plasmo.b62/wdk.log 
[25/Apr/2023|14:42:55] sid:      rid:                                - INFO  - org.gusdb.wdk.cache.FilterSizeCache$1:167 - Notification of steps modification, step IDs: [  ]
[25/Apr/2023|14:42:55] sid:27085 rid: 1698449     573ms   172.20.190.56 - ERROR - org.gusdb.wdk.service.service.SessionService:127 - Unsuccessful login attempt:  Redirect /plasmo/app/user-comments/add?stableId=PF3D7_1133400&commentTargetId=gene&externalDbName=pfal3D7_primary_genome_RSRC&externalDbVersion=2020-09-01&organism=Plasmodium falciparum&locations=1292966-1296696&contig=Pf3D7_11_v3&strand=+ not a valid URI.
org.gusdb.wdk.model.WdkModelException: Redirect /plasmo/app/user-comments/add?stableId=PF3D7_1133400&commentTargetId=gene&externalDbName=pfal3D7_primary_genome_RSRC&externalDbVersion=2020-09-01&organism=Plasmodium falciparum&locations=1292966-1296696&contig=Pf3D7_11_v3&strand=+ not a valid URI.
	at org.gusdb.wdk.service.service.SessionService.createRedirectResponse(SessionService.java:283) ~[wdk-service-1.0.0.jar:?]
	at org.gusdb.wdk.service.service.SessionService.getSuccessResponse(SessionService.java:205) ~[wdk-service-1.0.0.jar:?]
	at org.gusdb.wdk.service.service.SessionService.processOauthLogin(SessionService.java:124) ~[wdk-service-1.0.0.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor4862.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

![Screen Shot 2023-04-25 at 2 39 00 PM](https://user-images.githubusercontent.com/16354313/234372513-b3e8caed-d2cb-4e1c-9578-d652df44dabe.png)

**Comment by ryanrdoherty** [comment]
This happens because, unlike most redirect URLs, the redirect URL passed to the OAuth server in the comments case is not an absolute URL (i.e. starting with https://domain... etc).   I suspect there is some custom code for this pop-up that only sends the path portion of the URL and this is an easy fix if you know where to look.
